#pragma once
#include "../utils/utils.h"

#include "_structs.h"
#include "definitions.h"

#include "datatypes/bf_read.h"
#include "datatypes/bf_write.h"
#include "datatypes/recv_prop.h"
#include "datatypes/client_class.h"
#include "datatypes/c_utl_vector.h"
#include "datatypes/c_cvar.h"
#include "datatypes/i_material_var.h"
#include "datatypes/i_material.h"

#include "other/i_collideable.h"
#include "other/i_client_entity.h"
#include "datatypes/c_base_handle.h"

#include "interfaces/i_mem_alloc.h"
#include "interfaces/i_client_entity_list.h"
#include "interfaces/i_base_client_dll.h"
#include "interfaces/i_global_vars.h"
#include "interfaces/i_client_mode.h"
#include "interfaces/i_net_channel.h"
#include "interfaces/i_engine_client.h"
#include "interfaces/i_client_state.h"
#include "interfaces/i_surface.h"
#include "interfaces/i_input.h"
#include "interfaces/i_move_helper.h"
#include "interfaces/i_prediction.h"
#include "interfaces/i_game_movement.h"
#include "interfaces/i_debug_overlay.h"
#include "interfaces/i_cvar_system.h"
#include "interfaces/i_game_event_manager.h"
#include "interfaces/i_render_view.h"

#include "datatypes/i_trace_filter.h"
#include "datatypes/key_values.h"

#include "interfaces/i_model_info.h"
#include "interfaces/i_engine_trace.h"
#include "interfaces/i_surface_data.h"
#include "interfaces/i_input_system.h"
#include "interfaces/c_game_rules.h"
#include "interfaces/i_game_types.h"
#include "interfaces/i_mdl_cache.h"
#include "interfaces/i_model_render.h"
#include "interfaces/i_material_system.h"
#include "interfaces/i_glow_object_manager.h"
#include "interfaces/i_view_render_beams.h"
#include "interfaces/i_weapon_system.h"
#include "interfaces/c_cs_player_resource.h"
#include "interfaces/i_localize.h"
#include "interfaces/i_panel.h"

#include "_classes.h"
